###
POST http://localhost:8080/api/positions/events
Content-Type: application/json

[{
  "ID": 1,
  "Action" : "BUY",
  "account" : "ACC1",
  "security": "SEC1",
  "quantity": 1001
},
  {
    "ID": 2,
    "Action" : "BUY",
    "account" : "ACC1",
    "security": "SEC1",
    "quantity": 1
  },
  {
    "ID": 3,
    "Action" : "SELL",
    "account" : "ACC1",
    "security": "SEC1",
    "quantity": 1
  },

  {
    "ID": 1,
    "Action" : "CANCEL",
    "account" : "ACC2",
    "security": "SEC1",
    "quantity": 2
  }
]